version: '3.3'
services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - API_SUBSCRIPTION_KEY=${api_sub_key}
      - TOKENIZER_API_SUBSCRIPTION_KEY=${tokenizer_api_sub_key}
      - BIZ_COSMOS_ACCOUNT_PK=${biz_cosmos_account_pk}
      - RECEIPT_COSMOS_ACCOUNT_PK=${receipt_cosmos_account_pk}
      - STORAGE_ACCOUNT_PK=${storage_account_pk}
      - VARS=${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

