version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:9e37f3209c16af8c17a79cf3a5f7d4402673726de4c7e25572d189acf06405c5
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
      - '${PWD}/src/resources:/resources'
    environment:
      - VARS=${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
      - API_SUBSCRIPTION_KEY=${API_SUBSCRIPTION_KEY}
      - TOKENIZER_API_SUBSCRIPTION_KEY=${TOKENIZER_API_SUBSCRIPTION_KEY}
      - BIZ_COSMOS_ACCOUNT_PRIMARY_KEY=${BIZ_COSMOS_ACCOUNT_PRIMARY_KEY}
      - RECEIPT_COSMOS_ACCOUNT_PRIMARY_KEY=${RECEIPT_COSMOS_ACCOUNT_PRIMARY_KEY}
      - STORAGE_ACCOUNT_PRIMARY_KEY=${STORAGE_ACCOUNT_PRIMARY_KEY}      
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:447a8665cc1dab95b1ca778e162215839ccbb9189104c79d7ec3a81e14577add
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

