oa3_spec: ./openapi/openapi_lap_jwt.json
name: opex_pagopa-bizevents-service
location: West Europe
timespan: 5m
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-p-app-gw
resource_type: app-gateway
# data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
# resource_type: api-management
action_groups:
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/Opsgenie
overrides:
  hosts:
    - api.platform.pagopa.it
  base_path: "/bizevents/notices-service-jwt/{version}"
  endpoints:
    GET /info:
      availability_threshold: 0.90 # Default: 99%
    GET /paids:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    GET /paids/{event-id}:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    POST /paids/{event-id}/disable:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    GET /paids/{event-id}/pdf:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    GET /transactions:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    GET /transactions/{event-id}/pdf:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    GET /transactions/{transaction-id}:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%
    POST /transactions/{transaction-id}/disable:
      response_time_threshold: 9 # Default: 1
      availability_threshold: 0.80 # Default: 99%