name: Deploy on AKS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: The name of the environment where to deploy
        type: string
      branch:
        required: false
        default: ${{ github.ref_name }}
        type: string
      suffix_name:
        required: false
        default: ''
        type: string
      traffic_weight:
        required: false
        type: string
        default: "0"
        description: 'The percentage of traffic to be sent to the canary version'
      is_canary:
        type: boolean
        description: 'Mark the release as canary on AKS'
        default: false
      image_tag:
        required: false
        type: string
        default: ''
    secrets:
      CD_CLIENT_ID:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true

env:
  APP_NAME: pagopabizeventsservice


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [ self-hosted-job, "${{ inputs.environment }}" ]
    name: Deploy on AKS
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy
        uses: pagopa/github-actions-template/aks-deploy@525266fb788f4da438e5919fcf660fe8637271ed # 2.2
        with:
          branch: ${{ inputs.branch }}
          client_id: ${{ secrets.CD_CLIENT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          env: ${{ inputs.environment }}
          namespace: ${{ vars.NAMESPACE }}
          cluster_name: ${{ vars.CLUSTER_NAME }}
          resource_group: ${{ vars.CLUSTER_RESOURCE_GROUP }}
          app_name: ${{ env.APP_NAME }}${{inputs.suffix_name}}
          helm_upgrade_options: >-
            --debug
            --set microservice-chart.azure.workloadIdentityClientId=${{ vars.WORKLOAD_IDENTITY_ID }}
            --set microservice-chart.canaryDelivery.create=${{ inputs.is_canary }}
            --set microservice-chart.canaryDelivery.ingress.weightPercent=${{ inputs.traffic_weight }}
            ${{ inputs.is_canary && '--set microservice-chart.fullnameOverride=pagopabizeventsservice-canary' || '' }}
            ${{ inputs.is_canary && inputs.image_tag != '' && format('--set microservice-chart.canaryDelivery.image.tag={0}', inputs.image_tag) || '' }}
          timeout: '15m0s'